# Generated by Django 4.1.5 on 2023-02-04 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KitaplikModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('yazar', models.CharField(max_length=200)),
                ('yayin_tarihi', models.DateField()),
                ('tur', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('kayit_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('yayin_durumu', models.BooleanField(default=False)),
            ],
        ),
    ]
