# Generated by Django 4.1.5 on 2023-02-04 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haberbaslik', models.CharField(max_length=250)),
                ('haberozet', models.TextField()),
                ('habericerik', models.TextField()),
                ('haberkayitzaman', models.DateTimeField(default=django.utils.timezone.now)),
                ('haberyayimzaman', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
