#Generated by Django 4.1.5 on 2023-02-05 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('yazi', models.TextField(verbose_name='Yazı Gövdesi')),
                ('kayitzaman', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kayıt Zaman')),
                ('yayimzaman', models.DateTimeField(blank=True, null=True, verbose_name='Yayımlanma Zamanı')),
            ],
            options={
                'verbose_name': 'Gönderi',
                'verbose_name_plural': 'Gönderiler',
            },
        ),
    ]