# Generated by Django 4.1.5 on 2023-02-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_baslik', models.CharField(max_length=250)),
                ('makale_konu', models.CharField(max_length=100)),
                ('makale_yazi', models.TextField()),
                ('makale_yayimzaman', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
